// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Onion.Persistance.Context;

#nullable disable

namespace Onion.Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230830192432_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Onion.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("87b35ef7-725a-40d3-bdba-0d083f3bf211"),
                            CreationDate = new DateTime(2023, 8, 30, 19, 24, 32, 608, DateTimeKind.Utc).AddTicks(8673),
                            Name = "Mask",
                            Price = 19.99m,
                            Quantity = 50
                        },
                        new
                        {
                            Id = new Guid("8fa52cc9-4891-499e-8d28-2066d380b037"),
                            CreationDate = new DateTime(2023, 8, 30, 19, 24, 32, 608, DateTimeKind.Utc).AddTicks(8688),
                            Name = "Knife",
                            Price = 250.99m,
                            Quantity = 10
                        },
                        new
                        {
                            Id = new Guid("d5e89339-114e-40c4-ba58-3259ec466256"),
                            CreationDate = new DateTime(2023, 8, 30, 19, 24, 32, 608, DateTimeKind.Utc).AddTicks(8690),
                            Name = "Glove",
                            Price = 350.99m,
                            Quantity = 85
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
